### ISSUE TITLE
State mutation in middleware

### ISSUE THREAD

**Issue by newah** [manicantic/react-native-navigation-redux-integration#3]
Awesome library. 

But due to few crashes/inconsistencies, can't really use it.

using reduxImmutableStateInvariant gives this: ![Simulator Screen Shot - iPhone X - 2019-04-25 at 10 26 12](https://user-images.githubusercontent.com/7869178/56717107-a2e71100-6744-11e9-9712-6604f652c0c7.png)

Second issue is when:
1) user logs in, root changes
2) new root has bottom tabs
3) we automatically change bottom tab index after views initiated. this leads to situation shown in the image

If I remove automated tab changing upon loading, it seems to work as expected.

Edit:
same issue exists when changing tabs manually, too.

<img width="372" alt="Screen Shot 2019-04-25 at 10 30 05" src="https://user-images.githubusercontent.com/7869178/56717356-243ea380-6745-11e9-9193-46091c539d85.png">

**Comment by newah** [comment]
Actually after "TAB_CHANGED" action root gets undefined, so maybe that's the issue
<img width="633" alt="Screen Shot 2019-04-25 at 10 41 40" src="https://user-images.githubusercontent.com/7869178/56718106-d0cd5500-6746-11e9-93c6-c03148fbda56.png">

**Comment by manicantic** [comment]
HI @newah, thanks for a reporting. I will take a deeper look today. But I have a question, do you set selectedTabIndex with setRoot or do you call mergeOptions afterwards ? Because I notices that unselectedTabIndex is 2, but in prev state activeIndex is 0. That's where bug might be and I will take a look

**Comment by manicantic** [comment]
Hi @newah . I pushed 0.3.7 with fix when setting layout with currentTabIndex property. Can you check it out and see if that fix issue for you ?

**Comment by newah** [comment]
@manicantic awesome! will try to check tomorrow :) 

And I tried both: setting it via setRoot, not setting initial tab index at all, setting via mergeOptions... :)

**Comment by manicantic** [comment]
@newah Did 0.3.7 fix your issue ?

**Comment by newah** [comment]
@manicantic sorry for late response. Works as expected now! :)

though still a bit disturbing is the fact that state mutations still happen with PUSH and POP actions
![Simulator Screen Shot - iPhone X - 2019-05-23 at 16 09 47](https://user-images.githubusercontent.com/7869178/58255368-82c36580-7d75-11e9-872c-3782b2b55cb4.png)

**Comment by manicantic** [comment]
@newah Thanks for the feedback, and for this state mutation I will take a look soon :)

**Comment by newah** [comment]
It's not a blocker anymore. rather just something that's not by the default guidelines ;) Thanks
